# 공통 설정
server:
  port: 8080
spring:
  application:
    name: api-server
  profiles:
    active: dev # 기본 활성 프로필을 dev로 지정
    group:
      "dev": "dev,local"
      "prod": "prod,local"
#  cache:
#    type: redis
#    redis:
#      time-to-live: 600000 # 10분 (밀리초)
#  jpa:
#    hibernate:
#      ddl-auto: update # 개발 초기에는 create 또는 update 사용
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  batch:
#    jdbc:
#      initialize-schema: always  # never, always 외부 DB에서는 Batch 스키마 수동 초기화 추천
#    job:
#      enabled: false
#  sql:
#    init:
#      mode: always